### ISSUE TITLE
Test macOS, Windows builds on pull-requests

### ISSUE THREAD

**Issue by arbourd** [fishworks/fish-food#1124]
Right now the Github Actions CI only tests against a Linux install. This allows PRs that work for Linux to pass, but maybe issues like #1122 to arise with other platforms.

Should we tests against the other platforms? Future CI could look like:
1. step: `gofish lint`
2. if 1. passes, matrix `gofish install` on all platforms

This would make all builds longer, and requires the downloading of assets twice (once for the lint step, again for the install step -- this could be fixed with asset caching), but would ensure that all platforms have installable binaries.

**Comment by arbourd** [comment]
Is something you would be interested in entertaining @bacongobbler? If not I can close it. nbd.

**Comment by bacongobbler** [comment]
Please feel free to look into this. I’m on holiday break.

**Comment by arbourd** [comment]
Like most things I under estimated how much work this could be. Couple of issues I've experienced:

1. Obvious differences between `pwsh` and `bash`. Should we use `pwsh` for Windows or just `bash` on all platforms? There are some issues with getting `gofish tank` working in the Linux subsystem because it's not `eval`able.
2. We need a way to determine if the Food supports the current architecture/platform. `gofish` will return 1 if you try to `gofish install vagrant` on Darwin for example. Easiest way to handle this is regex for `os = "darwin"`. Any good alternatives?

**Comment by bacongobbler** [comment]
> There are some issues with getting gofish tank working in the Linux subsystem because it's not evalable.

[huh?](https://github.com/fishworks/fish-food/blob/main/.github/workflows/pr-test.yml#L30)

You could try catching that error message and exit if another error message is found.

**Comment by arbourd** [comment]
>huh? It was designed to be eval-able.eval is the primary use case for gofish tank.

Ya, but in Windows' Linux Subsystem and with `bash`, `eval $env.GOFISH_HOME` won't work. Would need `export` style script.

If the Windows tests are to be completely in `pwsh` (and not using bash/subsystem), `gofish.exe tank | iex` works juuuust fine 🙂 If we want to use `bash` in Windows we'll need some sort of alternative to export the env vars.
