### ISSUE TITLE
jq `1.6` keeps "upgrading"

### ISSUE THREAD

**Issue by arbourd** [fishworks/fish-food#1138]
`jq` keeps reinstalling. Could this be due to the lack of traditional semver (`1.6` vs. `1.6.0`)?

<img width="289" alt="Screen Shot 2020-12-27 at 1 05 14 PM" src="https://user-images.githubusercontent.com/7211830/103177002-3b9c3100-4844-11eb-91ab-1dd06d5a1797.png">

**Comment by bacongobbler** [comment]
That is possible, yes.

**Comment by arbourd** [comment]
Correctly installed into its `1.6` path in barrel, but ya the semver package is parsing it as `1.6.0` for comparisons. I see two paths to prevent this:

1. We set the jq package version to `1.6.0`
2. We change how gofish handles version parsing

2 is obv way more impact than 1. I'm not sure if we would ever want 2.
