### ISSUE TITLE
Escape `@<username>` mentions in PRs produced by bot

### ISSUE THREAD

**Issue by hiddeco** [fishworks/fish-food#1346]
While I am much supportive of (and very happy with) the automated distribution of the goods we produce, the behavior of the bot to copy and paste the release notes including `@<username>` mentions creates a lot of noise in my already hard to track notifications.

It would therefore be awesome if the bot could detect and modify username mentions, so that I no longer receive pings for something that is out of my hands.

The best way to do this at present is described in: https://github.com/github/markup/issues/1168#issuecomment-494946168

**Comment by mogensen** [comment]
Sounds like a good addition. I will take a look at that soon. ;)

**Comment by bacongobbler** [comment]
FUI, the gofish-bot source code can be found here: https://github.com/gofish-bot/gofish-bot

@mogensen is the maintainers of said bot, so he would know what’s involved here. :)

**Comment by andreykaipov** [comment]
That's funny - one of those automatic PRs helped me find this project. Gives me another cool package manager to try. I totally agree with escaping the usernames for less spam, but figured I'd share this little anecdote! 😄

**Comment by dholbach** [comment]
I asked for this in https://github.com/fishworks/fish-food/pull/1233#issuecomment-780480690 as well.

**Comment by mogensen** [comment]
Hey guys.
Sorry for the spam. And sorry @dholbach for missing your earlier request.

I have added a step to clean the markdown https://github.com/gofish-bot/gofish-bot/commit/3d26b62e01e7ad0c9a5692637ebf057949359e61

I hope this solves the problem.
Create an Issue at gofish-bot/gofish-bot if you see that I have missed something, Github is quite aggressive with linking.. ;)

@bacongobbler I believe we can close this one. Thanks for all the good work!

**Comment by hiddeco** [comment]
Thank you very much for following through @mogensen, I can see in https://github.com/fishworks/fish-food/pull/1357 that it works as expected. :100: :heart:
