### ISSUE TITLE
squashctl sha256 check is broken

### ISSUE THREAD

**Issue by bacongobbler** [fishworks/fish-food#180]
Looks like the squashctl team might've re-uploaded a new version of squashctl which broke existing shasums, as the binaries have changed. @scranton, would you mind taking a look into this?

See https://circleci.com/gh/fishworks/fish-food/440 for context.

**Comment by scranton** [comment]
will do... kicking off a new release of squash as the GitHub release shas
are out of sync with the binaries. expect an updated formula in an hour or
so. Thanks!!

BTW: enjoyed your helm 3 posts, and looking forward to helm 3 GA!

Scott Cranton
Solo.io <https://www.solo.io/> | Customer Success
scott.cranton@solo.io
+1.781.929.0056

**Comment by bacongobbler** [comment]
Fixed in #182. Thanks Scott for the follow-up and for the kind words :)
