### ISSUE TITLE
Add info about uff in Readme

### ISSUE THREAD

**Issue by karuppiah7890** [fishworks/fish-food#248]
I recently created a new tool called [uff](https://github.com/karuppiah7890/uff) - update fish food. It's a small and bit hacky tool to update a gofish food that I used to raise some PRs recently.

Anyone can use the tool to update the fish food with ease, in most cases. So I thought may be we can mention it in the readme so that if anyone wants to raise a PR it's just very easy and automated too

**Comment by bacongobbler** [comment]
closing as inactive
