### ISSUE TITLE
GoFish-bot for updating fish food

### ISSUE THREAD

**Issue by fmotrifork** [fishworks/fish-food#249]
Hi,

I have started developing a bot that can create pull-requests when existing fish food gets new releases.

For now it is still quite simple and rough around the edges.
I will make the code open-source, when i have added a few safe guards. 
It still needs to learn to only create pull requests for new releases, and not open multiple PRs for the same package/release multiple times.. ;)

https://github.com/gofish-bot

So this is just a heads-up that GoFish-bot will start trying to be an active contributor to the fish-food repo. :smile: :robot:

**Comment by bacongobbler** [comment]
This is FANTASTIC! Thank you for working on this!
