### ISSUE TITLE
Error when use gofish install cli

### ISSUE THREAD

**Issue by yJunS** [fishworks/fish-food#267]
when I use GoFish install jcli plugin on windows 10 environment:
PS C:\WINDOWS\system32> gofish.exe init
The following new directories will be created:
C:\ProgramData\Fish
C:\ProgramData\Fish\Barrel
C:\ProgramData\Fish\Rigs
C:\ProgramData\bin
C:\Users\SyJun\AppData\Local\Fish
==> Installing default fish food...
Error: Unable to get repository: Cloning into 'C:\ProgramData\Fish\Rigs\github.com\fishworks\fish-food'...
fatal: Invalid path '/cygdrive/c/WINDOWS/system32/C:\ProgramData\Fish\Rigs\github.com\fishworks\fish-food': No such file or directory
: exit status 128
PS C:\WINDOWS\system32> gofish.exe update
==> Rigs updated!
NAME

🐠  rigs updated in 1.0011ms
PS C:\WINDOWS\system32> gofish install jcli
Error: no fish food with the name 'jcli' was found

**Comment by bacongobbler** [comment]
Did you install gofish with cygwin, or are running commands under cygwin? Looks like the home path is incorrect.

**Comment by bacongobbler** [comment]
```
fatal: Invalid path '/cygdrive/c/WINDOWS/system32/C:\ProgramData\Fish\Rigs\github.com\fishworks\fish-food': No such file or directory
: exit status 128
```

**Comment by LinuxSuRen** [comment]
`gofish init` is failed. So the following install cmd will be failed too.

**Comment by yJunS** [comment]
Will Cygwin64 Terminal be affected when I install it in Windows 10?

**Comment by yJunS** [comment]
I run 'gofish init' successful on git bash . but when I run 'gofish install jcli' it tips 'Error: food 'jcli' does not support the current platform (windows/amd64)'

**Comment by bacongobbler** [comment]
That's because jcli only supports 32 bit architectures as per https://github.com/fishworks/fish-food/blob/311ed511b210a37e35f147489fcc3d6114bc9552/Food/jcli.lua#L39

If that CLI also works on 64-bit architectures, then the package should be updated to support the windows/amd64 platform.

**Comment by LinuxSuRen** [comment]
@bacongobbler Thanks to pointing this.

@yJunS You can download the binary file by manual. Test it whether it's ok.
