### ISSUE TITLE
CI: only test food that has changed in a PR

### ISSUE THREAD

**Issue by fmotrifork** [fishworks/fish-food#479]
I would propose reimplementing the Circle CI tests on PRs, so that only the foods that has been changed is tested.
This could help us in actually identifying which PRs are good and which are bad.

If we still want to validate all foods on a regular basis this could be done with a weekly report/alert?

**Comment by bacongobbler** [comment]
good suggestion. If you feel like tackling this one feel free! This would certainly help out with reviewing individual version bumps. That way packages can continue to be updated without requiring other unrelated packages to be fixed.

**Comment by bacongobbler** [comment]
updated the title to better reflect the ask
