### ISSUE TITLE
Problem upgrading Linkerd that does not follow Semantic Versioning

### ISSUE THREAD

**Issue by fmotrifork** [fishworks/fish-food#854]
There's currently a problem in upgrading the linkerd food.

The problem seems to be that the version, that Linkerd published, does not follow Semantic Versioning.

```bash
$ gofish update && gofish upgrade
==> Rigs updated!
NAME                          
github.com/fishworks/fish-food

🐠  rigs updated in 6.333312243s
==> Rigs updated!
NAME                          
github.com/fishworks/fish-food

🐠  rigs updated in 2.458226787s
==> Upgrading buffalo...
🐠  buffalo 0.16.10: upgraded in 32.57126ms
Error: Error parsing version: Invalid Semantic Version
```

I see a couple of problems here that I think should be addressed:

 - Linkerd food is broken.
 - It is not possible to identify from the error message which food is actually the problem.
 - The Linkerd lints and installs fine, but does not work when upgrading.

I can create a new PR with a better version, but I think that this may also require some cleanup on machines where the Linkerd Food is installed?

**Comment by bacongobbler** [comment]
I'm not too concerned about requiring some cleanup to "forward-fix" broken packages.

however I do agree that we should try to address this issue. I filed https://github.com/fishworks/gofish/issues/165 to help catch these scenarios going forward. Once that's implemented, any packages introduced with invalid semver versions will fail and will need to be fixed.
